### ISSUE TITLE
[Doc] Update maintainer doc

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/opensearch-dashboards-functional-test#212]
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/MAINTAINERS.md

**Comment by seraphjiang** [comment]
nominate @tianleh @kavilla @Tengda-He @ohltyler @CCongWang @davidcui1225 

https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#becoming-a-maintainer

**Comment by seraphjiang** [comment]
@tianleh is there any update?

**Comment by seraphjiang** [comment]
what does update directly means?

could we raise a PR for proposed maintainer list?

**Comment by tianleh** [comment]
"Update directly" means raising PR to update this [section](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/MAINTAINERS.md#current-maintainers). The standard process has a voting [process](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#becoming-a-maintainer) which I think is not yet applicable to this repo since we do not have the initial list of actual maintainers configured so far.

**Comment by seraphjiang** [comment]
make sense, let's go with direct PR~
