### ISSUE TITLE
Remove "npx" to run cypress directly

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#47]

**Comment by tianleh** [comment]
Following the Cypress doc
https://docs.cypress.io/guides/guides/command-line#How-to-run-commands

Tried both

```
$(npm bin)/cypress run

...or...

./node_modules/.bin/cypress run

```

They all work. Thus `npx` is not a hard requirement. But if `npx` comes for free with `npm`, then we'd like keeping the current command with `npx`.

**Comment by tianleh** [comment]
@peterzhuamazon @Tengda-He @seraphjiang

**Comment by Tengda-He** [comment]
why do we want to remove "npx" at the beginning ?

**Comment by tianleh** [comment]
Peter wants to see the possibility to remove the library npx so that the Docker image is simplified.

**Comment by ohltyler** [comment]
From my understanding npx is just used for downloading & caching packages on-the-fly to run them. Since cypress is already a hard dependency and explicitly stored in the codebase, I believe we can remove npx altogether.

For where it's used in github actions ([example](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/.github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml#L69)), it can be replaced with [this cypress action](https://github.com/cypress-io/github-action) which handles the installing/caching of cypress.

For where it's used in the [integTest.sh script](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/integtest.sh#L90), it can be removed, since after bootstrapping the plugin and downloading all of the dependencies, cypress should be available locally, as specified in [package.json](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/package.json#L25) and installed in node_modules from the relevant bootstrap command (e.g., `npm install`).

**Comment by ohltyler** [comment]
cc @tianleh @peterzhuamazon  ^^

**Comment by peterzhuamazon** [comment]
You can simply cypress run, but for some custom runs in observability plugin and others you can `yarn cypress:test` or `npx cypress:test` to run specific configured test.

I dont necessarily think we need to completely remove it, just let developers decide what to use in integTest.sh.

**Comment by ohltyler** [comment]
Sure, I'm just referring to this repo specifically, and the tests that plugin teams migrate over to it. In which case we don't need to use `npx` since cypress is already installed and configured.

I'm not sure what reasons teams would be using npx for specifically, are you aware at all? Do they not want to store cypress as a dependency locally when developing?

**Comment by peterzhuamazon** [comment]
> Sure, I'm just referring to this repo specifically, and the tests that plugin teams migrate over to it. In which case we don't need to use `npx` since cypress is already installed and configured.
> 
> I'm not sure what reasons teams would be using npx for specifically, are you aware at all? Do they not want to store cypress as a dependency locally when developing?

Observability for example, has TZ information to set before the cypress run happens, and it is using yarn/npx to do so by defining a test in package.json:
https://github.com/opensearch-project/observability/blob/main/dashboards-observability/package.json#L10-L11

If you dont need such thing, feel free to run cypress run directly. I would recommend to use yarn over npx, as we have yarn by default, but probably not npx in test image.

**Comment by ohltyler** [comment]
> > Sure, I'm just referring to this repo specifically, and the tests that plugin teams migrate over to it. In which case we don't need to use `npx` since cypress is already installed and configured.
> > I'm not sure what reasons teams would be using npx for specifically, are you aware at all? Do they not want to store cypress as a dependency locally when developing?
> 
> Observability for example, has TZ information to set before the cypress run happens, and it is using yarn/npx to do so by defining a test in package.json: https://github.com/opensearch-project/observability/blob/main/dashboards-observability/package.json#L10-L11
> 
> If you dont need such thing, feel free to run cypress run directly. I would recommend to use yarn over npx, as we have yarn by default, but probably not npx in test image.

Understood - agreed about using yarn over npx, since there shouldn't be any need to cache / download dependencies on the fly. In fact the workflows for this repo are already using yarn to trigger the cypress tests, and I just opened #89 which adds more custom commands, including adding TZ information before running the tests

**Comment by tianleh** [comment]
Already addressed https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/integtest.sh
