### ISSUE TITLE
[Main] onboard Dashboards plugins to functional test repo

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-dashboards-functional-test#72]
This issue is to track the overall progress of onboarding Dashboards plugins to the functional test repo. This is the [onboarding instruction](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md#onboarding)

- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/79
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/73
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/78
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/77
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/76
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/75
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/74
- [x] https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/82

**Comment by anirudha** [comment]
is there a doc or link that explains the motivation and goal on this issue ? , thanks

**Comment by anirudha** [comment]
how do we define " release tests" 
as per 

> https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md#onboarding

should all cypress tests be called release tests ?

**Comment by davidcui1225** [comment]
For long-term code maintenance does this mean that we will be maintaining cypress tests both in the `opensearch-dashboards-functional-test` repo and our plugin repo? How come the tests exist in 2 different places?

**Comment by tianleh** [comment]
> how do we define " release tests" as per
> 
> > https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md#onboarding
> 
> should all cypress tests be called release tests ?

Release tests are tests used for signing off. It could be all or a subset of the Cypress tests.

**Comment by tianleh** [comment]
> For long-term code maintenance does this mean that we will be maintaining cypress tests both in the `opensearch-dashboards-functional-test` repo and our plugin repo? How come the tests exist in 2 different places?

To address this, you can follow AD's example to move all Cypress tests in this repo https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/.github/workflows/remote-integ-tests-workflow.yml

**Comment by tianleh** [comment]
@bowenlan-amzn could you move your thoughts about the development process from https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/107 to this main issue?

**Comment by bowenlan-amzn** [comment]
> @bowenlan-amzn could you move your thoughts about the development process from #107 to this main issue?

We experienced an ISM test failure because of the test code was not synchronized from plugin repo to this functional test repo.

This is an evidence that we should proactively advise plugin owners to **remove** the test from their plugin repo once they migrate them here. Only keeps one source of cypress test.
And if we advise this, a subsequent question is how would plugin owner run the test now in this functional test repo during the plugin feature development.

Here are some basic thoughts:
1. First develop and merge the change of new plugin feature in the plugin repo.
2. Write corresponding cypress test for the new plugin feature in the functional test repo.
3. Use a GitHub workflow in plugin repo to run the cypress test in this functional test repo. We can trigger this GitHub workflow by daily and [manually](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)

**Comment by tianleh** [comment]
Since all issues have been closed, I am closing this main issue!
