### ISSUE TITLE
[2.9] Flaky tests in Opensearch Dashboards functional tests

### ISSUE THREAD

**Issue by manasvinibs** [opensearch-project/opensearch-dashboards-functional-test#768]
Even though CI build test results shows test failures for OSD, the video of the test shows it passing.

**Comment by kavilla** [comment]
Just an update the tests were ran multiple times but the videos were not updated. So indicates the test results for 2.9 have some flakey tests from OSD core

**Comment by kavilla** [comment]
for 2.10 so this failure occassionaly:
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/4162/pipeline

**Comment by kavilla** [comment]
addressed some in 2.10 but didn't get all of them with security installed.

**Comment by raintygao** [comment]
Hi @kavilla , I saw there is a PR https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/893/files skiping flaky test mentioned this issue, it may be related to OSD, could you fix it into a non flakey version?

**Comment by kavilla** [comment]
> Hi @kavilla , I saw there is a PR https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/893/files skiping flaky test mentioned this issue, it may be related to OSD, could you fix it into a non flakey version?

Might have to revisit this. I think originally because i think its not directly related to OSD. But the way security is handled when security plugin is installed.

Theres a number of issues that cause the flakiness with security.

With security tests will cause an unauth call and then it will refresh to get a session and then proceed to forward the tests to the expected page. However, a lot of tests in the current structure do not expect these queue of calls as most tests get written without the security plugin installed. And when verified locally, with more performace, these queue of calls are quick. But on a limited virtual env that shares limited space can lead to these calls taking like 10-30 seconds. In this time some access to an index but cause the tests to spin. For the rendering part in OSD we should fix the bugs associated to that cc @ananzh .

But the ftrepo we might need to be creative to prevent failures. A number of a ways i tried mitigating this is overwriting the visit function, also tried to execute a before that at least attempts cause this auth before all tests. It usually ends up being problematic when people try to upload data. Perhaps we can compress saved data and start up the cluster with the data indices already available.

Theres also another issue with when security is ran is because with multitenancy, the global tenant is the .kibana however, when we execute these tests. The default tenant used is the private tenant. Which goes along the line of a lot of these tests using the default .kibana but then with security the requests are being made to like .kibana_user12344. This has caused an issue when we bulked upload and were targeting .kibana but since it was accessing data in the global tenant we had to write it to switch the tenant. Imo, the ftrepo should default use the global tenant and we should invert or switch the default tenant when the tests for security plugin is ran.

**Comment by raintygao** [comment]
> > Hi @kavilla , I saw there is a PR https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/893/files skiping flaky test mentioned this issue, it may be related to OSD, could you fix it into a non flakey version?
> 
> Hey @raintygao
> 
> Might have to revisit this. I think originally because i think its not directly related to OSD. But the way security is handled when security plugin is installed.
> 
> Theres a number of issues that cause the flakiness with security.
> 
> With security tests will cause an unauth call and then it will refresh to get a session and then proceed to forward the tests to the expected page. However, a lot of tests in the current structure do not expect these queue of calls as most tests get written without the security plugin installed. And when verified locally, with more performace, these queue of calls are quick. But on a limited virtual env that shares limited space can lead to these calls taking like 10-30 seconds. In this time some access to an index but cause the tests to spin. For the rendering part in OSD we should fix the bugs associated to that cc @ananzh .
> 
> But the ftrepo we might need to be creative to prevent failures. A number of a ways i tried mitigating this is overwriting the visit function, also tried to execute a before that at least attempts cause this auth before all tests. It usually ends up being problematic when people try to upload data. Perhaps we can compress saved data and start up the cluster with the data indices already available.
> 
> Theres also another issue with when security is ran is because with multitenancy, the global tenant is the .kibana however, when we execute these tests. The default tenant used is the [private tenant](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/cypress%2Futils%2Fcommands.js#L20). Which goes along the line of a lot of these tests using the default .kibana but then with security the requests are being made to like .kibana_user12344. This has caused an issue when we bulked upload and were targeting .kibana but since it was accessing data in the global tenant we had to write it to switch the tenant. Imo, the ftrepo should default use the global tenant and we should invert or switch the default tenant when the tests for security plugin is ran.

Hey @kavilla , thanks for your clarification, will discuss with team to see how to resolve. 
It looks like it involves a lot of test cases, there may be some that are ignored using the skip method, and some may fail due to these reasons. Do you know the approximate scope of the impact?

**Comment by raintygao** [comment]
> > Hi @kavilla , I saw there is a PR https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/893/files skiping flaky test mentioned this issue, it may be related to OSD, could you fix it into a non flakey version?
> 
> Hey @raintygao
> 
> Might have to revisit this. I think originally because i think its not directly related to OSD. But the way security is handled when security plugin is installed.
> 
> Theres a number of issues that cause the flakiness with security.
> 
> With security tests will cause an unauth call and then it will refresh to get a session and then proceed to forward the tests to the expected page. However, a lot of tests in the current structure do not expect these queue of calls as most tests get written without the security plugin installed. And when verified locally, with more performace, these queue of calls are quick. But on a limited virtual env that shares limited space can lead to these calls taking like 10-30 seconds. In this time some access to an index but cause the tests to spin. For the rendering part in OSD we should fix the bugs associated to that cc @ananzh .
> 
> But the ftrepo we might need to be creative to prevent failures. A number of a ways i tried mitigating this is overwriting the visit function, also tried to execute a before that at least attempts cause this auth before all tests. It usually ends up being problematic when people try to upload data. Perhaps we can compress saved data and start up the cluster with the data indices already available.
> 
> Theres also another issue with when security is ran is because with multitenancy, the global tenant is the .kibana however, when we execute these tests. The default tenant used is the [private tenant](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/cypress%2Futils%2Fcommands.js#L20). Which goes along the line of a lot of these tests using the default .kibana but then with security the requests are being made to like .kibana_user12344. This has caused an issue when we bulked upload and were targeting .kibana but since it was accessing data in the global tenant we had to write it to switch the tenant. Imo, the ftrepo should default use the global tenant and we should invert or switch the default tenant when the tests for security plugin is ran.

Hey @ananzh  will your team take a look on bugs associated with rendering part in OSD ?

**Comment by raintygao** [comment]
Team is working on each specific flaky test issue in FT repo, will close this issue as it's is a general one.
